package com.re.policyRuleSet
import java.util.*;
import com.re.util.*;
global RuleHelper ruleHelper;
global DroolsRuleLog droolsRuleLog;
global com.re.dm.MetaMap metaMap;
global java.util.Map dataMap;
dialect "mvel"
ruleflow-group "policyRuleSet_2_v1.00"


// ruleflow-group 与agendaGroup 效果等同
//政策规则集：同一个drl 欲中间变量在同一个规则drl 不同规则之间改变生效，不设置activation-group，按优先级排序所有满足条件的都可执行



rule "policyRuleSet_2_v1.00_test001"
//activation-group "policyRuleSet_2_v1.00_1"
salience 9999000
enabled true
when
    $insertMap : Map()
    Map(
    ruleHelper.getValue($insertMap,"input_keys.cust_age") <= 2
    )
 then
     ruleHelper.setValue($insertMap,"input_keys.cust_age","3") ;
     droolsRuleLog.addLogs("policyRuleSet","policyRuleSet_2_v1.00_test001",drools);
 end

rule "policyRuleSet_2_v1.00_test002"
//activation-group "policyRuleSet_2_v1.00_2"
salience 999800
enabled true
when
    $insertMap : Map()
    Map(
    ruleHelper.getValue($insertMap,"input_keys.cust_age") > 2 &&  ruleHelper.getValue($insertMap,"input_keys.cust_age") < 5
    )
 then
      ruleHelper.setValue($insertMap,"input_keys.cust_age","6") ;
      droolsRuleLog.addLogs("policyRuleSet","policyRuleSet_2_v1.00_test002",drools);
 end

rule "policyRuleSet_2_v1.00_test003"
//activation-group "policyRuleSet_2_v1.00_3"
salience 9997000
enabled true
when
    $insertMap : Map()
    Map(
    ruleHelper.getValue($insertMap,"input_keys.cust_age") >= 5
    )
 then
    ruleHelper.setValue($insertMap,"input_keys.cust_age","16") ;
       droolsRuleLog.addLogs("policyRuleSet","policyRuleSet_2_v1.00_test003",drools);
 end

 rule "policyRuleSet_2_v1.00_test004"
 //activation-group "policyRuleSet_2_v1.00_4"
 salience 9996000
 enabled true
 when
     $insertMap : Map()
     Map(
     ruleHelper.getValue($insertMap,"input_keys.cust_age") >=10
     )
  then
      ruleHelper.setValue($insertMap,"output_keys.cash_strgy_rslt","t04") ;
      ruleHelper.setValue($insertMap,"input_keys.cust_age","8") ;
      droolsRuleLog.addLogs("policyRuleSet","policyRuleSet_2_v1.00_test004",drools);
  end

rule updateInsertMap_uuid232
salience 2100000000
no-loop true
when
  $insertMap:Map()
then
   update($insertMap);
end